### ISSUE TITLE
cherrypy.wsgiserver no longer working

### ISSUE THREAD

**Issue by mauloop** [tiddlyweb/tiddlyweb#107]
I'm not experienced with Python and this is the first time I deal with Tiddlyweb. Maybe there are better ways to solve my issue than the ones I found on my own. Please tell me in that case.

I was trying to set up TiddlyWeb + TiddlyWebWiki. In these initial steps I intended to use the default http/wsgi server, but I found that since rel. 9.0.0 wsgiserver module has been removed from CherryPy (see https://github.com/cherrypy/cherrypy/issues/1585). Therefore, while running `twanager server`, it raised an import error:

<pre>
[mauloop@robin ~]$ twinstance tweb-test
[mauloop@robin ~]$ cd tweb-test/
[mauloop@robin tweb-test]$ cat tiddlywebconfig.py 
# A basic configuration.
# `pydoc tiddlyweb.config` for details on configuration items.

config = {
    'system_plugins': ['tiddlywebwiki'],
    'secret': '0bd83f7fdf480e07de554c1db4e8589e41bee046',
    'twanager_plugins': ['tiddlywebwiki'],
}
[mauloop@robin tweb-test]$ twanager server
ERROR: ImportError: No module named wsgiserver

   addrole: Add a role to an existing user. <username> [role] [role] [role]
   adduser: Add or update a user to the database: <username> <password> [[role] [role] ...]
       bag: Create or update a bag with the json text on stdin: <bag>
      info: Display info about TiddlyWeb.
  interact: Enter a Python interactive shell.
     lbags: List all the bags on the system. [<bag> <bag> <bag>] to limit.
  lrecipes: List all the recipes on the system. [<recipe> <recipe> <recipe>] to limit.
 ltiddlers: List all the tiddlers on the system. [<bag> <bag> <bag>] to limit.
    lusers: List all the users on the system. [<user> <user> <user>] to limit.
    recipe: Create or update a recipe with the recipe text on stdin: <recipe>
    server: Start the server using config settings. Provide <host name or IP number> <port> to override.
   tiddler: Import a single tiddler into an existing bag from stdin: <bag> <tiddler>
    update: Update the default tiddlers for this instance.
     usage: List this help
  userpass: Change the password of an existing user. <username> <password>
[mauloop@robin tweb-test]$ 
</pre>

I didn't like to downgrade CherryPy, so I found two ways to solve this issue:

- Add this config entry to tiddlywebconfig.py: `'wsgi_server': 'tiddlyweb.web.serve'`
- Patch `tiddlywebplugins/cherrypy.py` as suggested inthe CherryPy repo issue I linked above (it requires to have cheroot Python module installed)

This is the patched version of `tiddlywebplugins/cherrypy.py`

<pre>
"""
Replace the default (slow) wsgiref server with
a faster (because of threads) web server. Only
used if the instance is started with "twanager
server".

See the "wsgi_server" entry in tidddlyweb.config.

To use this add the following to tiddlywebconfig.py:::

    'wsgi_server': 'tiddlywebplugins.cherrypy'
"""
from __future__ import absolute_import

import logging
import sys

from tiddlyweb.util import std_error_message
from tiddlyweb.web.serve import load_app

LOGGER = logging.getLogger(__name__)

def start_server(config):
    #from cherrypy.wsgiserver import CherryPyWSGIServer
    try:
        from cheroot.wsgi import Server as WSGIServer
    except ImportError:
        from cherrypy.wsgiserver import CherryPyWSGIServer as WSGIServer
    hostname = config['server_host']['host']
    port = int(config['server_host']['port'])
    scheme = config['server_host']['scheme']
    app = load_app()
    #server = CherryPyWSGIServer((hostname, port), app)
    server = WSGIServer((hostname, port), app)
    try:
        #LOGGER.debug('starting CherryPy at %s://%s:%s',
        LOGGER.debug('starting WSGIServer at %s://%s:%s',
                scheme, hostname, port)
        #std_error_message("Starting CherryPy at %s://%s:%s"
        std_error_message("Starting WSGIServer at %s://%s:%s"
                % (scheme, hostname, port))
        server.start()
    except KeyboardInterrupt:
        server.stop()
        sys.exit(0)
</pre>

I choosed to run Tiddlyweb with the patched cherrypy plugin. It seems to work by now. Could this help someone? Is it possible to fix the issue in the official repo? 

Apologize if this was not the right place to post such issue.

P.S.: I noticed that there are no updates since 2016, nor posts in the Google group since more than one year ago. Is this project still alive?

**Comment by cdent** [comment]
> Is this project still alive?

It's not dead, but it is safe to say that TiddlyWeb is sort of resting. I continue to make daily use of services that rely on it, but not using the cherrypy server, so didn't run into it.

Your fix looks a step in the right direction. I'll look into making a new release of tiddlywebplugins-cherrypy.

Note that tiddlywebwiki (from when `twinstance` comes) is primarily oriented towards working with TiddlyWiki classic. There are ways to get TiddlyWiki 5 to work with TiddlyWeb, but it's been a while since I've worked with it.

Thanks very much for reporting this. I'll follow up here when I've created the new release. In the meantime, I hope your experiments continue to bear fruit.

**Comment by mauloop** [comment]
Thanks so much for your quick reply. Glad that this project is still alive. I think it's a great project.
I'm aware that make it work with TW5 could be a little bit harder, but I still intend to continue this way (at least I will say: "I tried it").

I've carefully read [this topic](https://groups.google.com/forum/m/#!topic/tiddlywiki/SevXd6y-Ha4) and your suggestions. 

I will check this issue for a new tiddlywebplugins-cherrypy release. BTW: CherryPy wsgi server is a good chance to start quickly. I plan to switch to Apache (or Nginx) as soon as I will have learned the basics of Tiddlyweb.

**Comment by cdent** [comment]
I've released a new tiddlywepblugins.cherrpy: https://pypi.python.org/pypi/tiddlywebplugins.cherrypy/0.2.0

While doing that I remembered that tiddlywebwiki still doesn't support python3. If I find the time I may attempt to address that, but it will require making changes in lots of different packages.

**Comment by mauloop** [comment]
Got it. It works for me. Tested serving default TWC or TW5 as well ("tested" means just opened the Tiddlywiki in the browser and quickly navigated some tiddlers).

This issue can be closed IMO.

**Comment by mauloop** [comment]
Some more tests. Added, modified and deleted tiddlers on TW5 from a browser running on localhost as well from a remote browser. Everything's all right.

**Comment by cdent** [comment]
Great. If you discover anything else, let us know. Thanks!
